from tkinter import *
import pdb


BOX_DIM = 50
NUM_BOX_WIDTH = 15
NUM_BOX_HEIGHT = 15
MAP_WIDTH = BOX_DIM * NUM_BOX_WIDTH
MAP_HEIGHT = BOX_DIM * NUM_BOX_HEIGHT

INFOBAR_WIDTH = NUM_BOX_WIDTH
INFOBAR_HEIGHT = 200

CANVAS_WIDTH = MAP_WIDTH
CANVAS_HEIGHT = MAP_HEIGHT + INFOBAR_HEIGHT

root = Tk()
can = Canvas(root, width=CANVAS_WIDTH, height=CANVAS_HEIGHT, bg='white')
